name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Theos Setup
        uses: NyaMisty/theos-action@master

      - name: Setup AltList
        run: |
          git clone https://github.com/opa334/AltList
          ./AltList/install_to_theos.sh
        
      - name: Build shadow
        run: ./build.sh
    